CREATE TABLE IF NOT EXISTS invitees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invite_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT,
  password_hash TEXT NOT NULL,
  max_guests INTEGER NOT NULL DEFAULT 2,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invitee_id INTEGER NOT NULL UNIQUE,
  attending INTEGER NOT NULL,
  guest_count INTEGER NOT NULL DEFAULT 0,
  dietary_notes TEXT,
  message TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invitee_id) REFERENCES invitees(id) ON DELETE CASCADE
);
